/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Forum } from "./Forum";
import { ForumCountArgs } from "./ForumCountArgs";
import { ForumFindManyArgs } from "./ForumFindManyArgs";
import { ForumFindUniqueArgs } from "./ForumFindUniqueArgs";
import { DeleteForumArgs } from "./DeleteForumArgs";
import { ForumService } from "../forum.service";
@graphql.Resolver(() => Forum)
export class ForumResolverBase {
  constructor(protected readonly service: ForumService) {}

  async _forumsMeta(
    @graphql.Args() args: ForumCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Forum])
  async forums(@graphql.Args() args: ForumFindManyArgs): Promise<Forum[]> {
    return this.service.forums(args);
  }

  @graphql.Query(() => Forum, { nullable: true })
  async forum(
    @graphql.Args() args: ForumFindUniqueArgs
  ): Promise<Forum | null> {
    const result = await this.service.forum(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Forum)
  async deleteForum(
    @graphql.Args() args: DeleteForumArgs
  ): Promise<Forum | null> {
    try {
      return await this.service.deleteForum(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
