/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Topic } from "./Topic";
import { TopicCountArgs } from "./TopicCountArgs";
import { TopicFindManyArgs } from "./TopicFindManyArgs";
import { TopicFindUniqueArgs } from "./TopicFindUniqueArgs";
import { DeleteTopicArgs } from "./DeleteTopicArgs";
import { TopicService } from "../topic.service";
@graphql.Resolver(() => Topic)
export class TopicResolverBase {
  constructor(protected readonly service: TopicService) {}

  async _topicsMeta(
    @graphql.Args() args: TopicCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Topic])
  async topics(@graphql.Args() args: TopicFindManyArgs): Promise<Topic[]> {
    return this.service.topics(args);
  }

  @graphql.Query(() => Topic, { nullable: true })
  async topic(
    @graphql.Args() args: TopicFindUniqueArgs
  ): Promise<Topic | null> {
    const result = await this.service.topic(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Topic)
  async deleteTopic(
    @graphql.Args() args: DeleteTopicArgs
  ): Promise<Topic | null> {
    try {
      return await this.service.deleteTopic(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
